/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowsRouteImport } from './routes/shows'
import { Route as HouseholdRouteImport } from './routes/household'
import { Route as ClothesRouteImport } from './routes/clothes'
import { Route as IndexRouteImport } from './routes/index'

const ShowsRoute = ShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdRoute = HouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => rootRouteImport,
} as any)
const ClothesRoute = ClothesRouteImport.update({
  id: '/clothes',
  path: '/clothes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clothes': typeof ClothesRoute
  '/household': typeof HouseholdRoute
  '/shows': typeof ShowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clothes': typeof ClothesRoute
  '/household': typeof HouseholdRoute
  '/shows': typeof ShowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clothes': typeof ClothesRoute
  '/household': typeof HouseholdRoute
  '/shows': typeof ShowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clothes' | '/household' | '/shows'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clothes' | '/household' | '/shows'
  id: '__root__' | '/' | '/clothes' | '/household' | '/shows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClothesRoute: typeof ClothesRoute
  HouseholdRoute: typeof HouseholdRoute
  ShowsRoute: typeof ShowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shows': {
      id: '/shows'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household': {
      id: '/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof HouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clothes': {
      id: '/clothes'
      path: '/clothes'
      fullPath: '/clothes'
      preLoaderRoute: typeof ClothesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClothesRoute: ClothesRoute,
  HouseholdRoute: HouseholdRoute,
  ShowsRoute: ShowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
